language: node_js
before_install:
  # R version installed by default apt-get is old. Use R mirror server instead.
  # http://askubuntu.com/questions/218708/installing-latest-version-of-r-base
  # 3.2.3 at the time of this writing.
  - echo "deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y ppa:marutter/rdev
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base
  - R --version
  #
  # Rserve version in R mirror server is old.
  # (SSL certificate for rforge.net has been expired since 2/11/2016. Remove --no-check-certificate option once updated)
  # 1.8.5 at the time of this writing.
  - wget --no-check-certificate https://rforge.net/Rserve/snapshot/Rserve_1.8-5.tar.gz
  - sudo R CMD INSTALL Rserve_1.8-5.tar.gz
  - R CMD Rserve --version
  # Use chromium browser in Travis.
  # http://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "4.3"
script:
  - npm test
  - npm run coveralls

# Node.js v4 compiler requirements on TravisCI
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
