language: node_js
before_install:
  - sudo add-apt-repository http://cran.cnr.berkeley.edu/bin/linux/ubuntu/precise/
  - cat /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base
  - sudo apt-get install -qq r-cran-rserve
  - R CMD Rserve --version
  - R --version
node_js:
  - "4.0"
  - "stable"
script:
  - npm test
  - npm run coveralls
