language: node_js
before_install:
  - echo "deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install r-base
  - sudo apt-get install r-cran-rserve
  - R CMD Rserve --version
  - R --version
node_js:
  - "4.0"
  - "stable"
script:
  - npm test
  - npm run coveralls
