language: node_js
before_install:
  - sudo deb https://cran.rstudio.com/bin/linux/ubuntu/ precise
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base
  - sudo apt-get install -qq r-base-dev
  - sudo apt-get install -qq r-cran-rserve
node_js:
  - "stable"
