language: node_js
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base
  - sudo apt-get install -qq r-cran-rserve
node_js:
  - "4.0"
  - "stable"
script:
  - npm test
  - npm coveralls
